services:
  web:
    image: "odoo:${VERSION}"
    container_name: "odoo-horebcorporation-${HOREBCORPORATION_VERSION}"
    user: root
    depends_on:
      - db
    ports:
      - "${HOREBCORPORATION_VERSION}069:8069"
      - "${HOREBCORPORATION_VERSION}072:8072"
    networks:
      - odoo_network_horebcorporation
    volumes:
      - "./v${VERSION}/odoo-web-data:/var/lib/odoo"
      - "./v${VERSION}/config/odoo.conf:/etc/odoo/odoo.conf"
      - "./v${VERSION}/addons:/mnt/extra-addons"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Set the password directly here

  db:
    image: postgres:16
    container_name: "odoo-db${HOREBCORPORATION_VERSION}"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Set the password directly here
      - POSTGRES_USER=odoo
      - PGDATA=${PGDATA}
    ports:
      - "${HOREBCORPORATION_VERSION}432:5432"
    networks:
      - odoo_network_horebcorporation
    volumes:
      - "./v${HOREBCORPORATION_VERSION}/pgdata:${PGDATA}"

volumes:
  odoo-web-data:
    name: "${APP:-myodoo}-web-v${HOREBCORPORATION_VERSION}"
  odoo-db-data:
    name: "${APP:-myodoo}-db-v${HOREBCORPORATION_VERSION}"

networks:
  odoo_network_horebcorporation:
    name: odoo_network_horebcorporation
