#Si no esta instalado ngnix, entonces corre el docker compose up -d


#Si esta instalado entonces restart el ngnix
#Paralevantar o restart el ngnix es 
#```bash
#sudo systemctl start nginx
#```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
