version: '3.1'

services:
  web:
    image: "odoo:${VERSION}"
    container_name: "odoo-${VERSION}"
    user: root
    depends_on:
      - db
    ports:
      - "${VERSION}069:8069"
      - "${VERSION}072:8072"
    networks:
      - odoo_network_17
    volumes:
      - "./v${VERSION}/odoo-web-data:/var/lib/odoo"
      - "./v${VERSION}/config/odoo.conf:/etc/odoo/odoo.conf"
      - "./v${VERSION}/addons:/mnt/extra-addons"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Set the password directly here

  db:
    image: postgres:15
    container_name: "odoo-db${VERSION}"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Set the password directly here
      - POSTGRES_USER=odoo
      - PGDATA=${PGDATA}
    ports:
      - "${VERSION}432:5432"
    networks:
      - odoo_network_17
    volumes:
      - "./v${VERSION}/pgdata:${PGDATA}"  # Aquí puedes cambiar el nombre del volumen

volumes:
  odoo-web-data:
    name: "${APP:-myodoo}-web-v${VERSION}"
  odoo-db-data:
    name: "${APP:-myodoo}-db-v${VERSION}-custom"  # Cambia el nombre aquí si lo deseas

networks:
  odoo_network_17:
    driver: bridge