services:
  web:
    image: "odoo:${VERSION}"
    container_name: "odoo-${VERSION}"
    user: root
    depends_on:
      - db
    ports:
      - "${VERSION}069:8069"
      - "${VERSION}072:8072"
    networks:
      - odoo_network_18
    volumes:
      - "./v${VERSION}/odoo-web-data:/var/lib/odoo"
      - "./v${VERSION}/config/odoo.conf:/etc/odoo/odoo.conf"
      - "./v${VERSION}/addons:/mnt/extra-addons"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Set the password directly here

  db:
    image: postgres:16
    container_name: "odoo-db${VERSION}"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Set the password directly here
      - POSTGRES_USER=odoo
      - PGDATA=${PGDATA}
    ports:
      - "${VERSION}432:5432"
    networks:
      - odoo_network_18
    volumes:
      - "./v${VERSION}/pgdata:${PGDATA}"
  n8n:
      image: n8nio/n8n
      container_name: "n8n-container"
      restart: unless-stopped
      ports:
        - "5678:5678"  # Puerto fijo para n8n (independiente de ${VERSION})
      networks:
        - odoo_network_18
      environment:
        - DB_TYPE=postgresdb
        - DB_POSTGRESDB_DATABASE=postgres  # Usa la misma DB que Odoo
        - DB_POSTGRESDB_HOST=db            # Nombre del servicio PostgreSQL
        - DB_POSTGRESDB_PORT=5432
        - DB_POSTGRESDB_USER=odoo          # Usuario existente
        - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}  # Misma contraseña
        - N8N_BASIC_AUTH_ACTIVE=true       # Seguridad básica (opcional)
        - N8N_BASIC_AUTH_USER=${N8N_USER}        # Cambia esto
        - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}    # Cambia esto
      volumes:
        - "./v${VERSION}/n8n_data:/home/node/.n8n"  # Persistencia de datos      

volumes:
  odoo-web-data:
    name: "${APP:-myodoo}-web-v${VERSION}"
  odoo-db-data:
    name: "${APP:-myodoo}-db-v${VERSION}"

networks:
  odoo_network_18:
    name: odoo_network_18